"""Core agent behavior."""

from .agent import Agent, DEFAULT_SYSTEM_PROMPT
from .context import (
    ContextPolicy,
    calculate_reserved_output_tokens,
    estimate_message_tokens,
    fit_messages,
    truncate_text,
)
from .chemicals import (
    CHEMICALS_SYSTEM_PROMPT,
    ChemicalsAgent,
    ChemicalsLoop,
    ChemicalsPhase,
    ChemicalsRun,
)
from .coding import (
    CODING_SYSTEM_PROMPT,
    ActionKind,
    ActionResult,
    CodingAction,
    CodingAgent,
    CodingLoop,
    CodingPlan,
    CodingPhase,
    CodingRun,
    CodingSession,
    CodingWorkspace,
    CODING_WORKFLOW,
    DOCUMENT_WORKFLOW,
    DocumentLifecycle,
    LocalWorkspace,
    PlanSource,
    ProgressOutput,
    WorkflowKind,
    WorkflowLifecycle,
    WorkflowProfile,
    WorkflowRoute,
    WorkflowRouter,
    create_coding_session,
    parse_action,
)

__all__ = [
    "Agent",
    "ActionKind",
    "ActionResult",
    "CHEMICALS_SYSTEM_PROMPT",
    "CODING_SYSTEM_PROMPT",
    "ChemicalsAgent",
    "ChemicalsLoop",
    "ChemicalsPhase",
    "ChemicalsRun",
    "CodingAgent",
    "CodingAction",
    "CodingLoop",
    "CodingPlan",
    "CodingPhase",
    "CodingRun",
    "CodingSession",
    "CodingWorkspace",
    "CODING_WORKFLOW",
    "ContextPolicy",
    "DEFAULT_SYSTEM_PROMPT",
    "DOCUMENT_WORKFLOW",
    "DocumentLifecycle",
    "LocalWorkspace",
    "PlanSource",
    "ProgressOutput",
    "WorkflowKind",
    "WorkflowLifecycle",
    "WorkflowProfile",
    "WorkflowRoute",
    "WorkflowRouter",
    "create_coding_session",
    "calculate_reserved_output_tokens",
    "estimate_message_tokens",
    "fit_messages",
    "parse_action",
    "truncate_text",
]
